---
sudo: required

language: python
python: 2.7
cache: pip

matrix:
  fast_finish: true

env:
  - TEST_RUN="./tests/test-minikube.sh"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y shellcheck
  - pip install -U -r test-requirements.txt

install:
  - "./scripts/install.sh"
  - "./scripts/bx_auth.sh"

before_script:
  - "./tests/test-shellcheck.sh"
  - "./tests/test-yamllint.sh"

script: "$TEST_RUN"
